GET http://localhost:8080/vehicles

###

POST http://localhost:8080/auth/signin
Content-Type:application/json

{
  "username":"user",
  "password":"password"}

###
GET http://localhost:8080/me
Authorization: Bearer  eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTU0MDY2NTMyMCwiZXhwIjoxNTQwNjY4OTIwfQ.DH_9Yiwh47PfjCfv3AevCRG-zNd1PrWU74gc3uYajqk
#{
#  "roles" : [ "ROLE_USER" ],
#  "username" : "user"
#}

###

